### PR TITLE
New example

### PR DESCRIPTION
**Pull request by danpovey**

### CODE REVIEW

**Comment by danpovey** [comment]
Some notes:
I added the file Example2_StartRTCMBase.cpp, which is modified from SparkFun_u-blox_GNSS_Arduino_Library/examples/NEO-M8P-2/Example2_StartRTCMBase/Example2_StartRTCMBase.ino  and
changed a bit to compile on Linux.  The changes just consisted of adding missing includes, replacing a type-cast
to string with a type-cast to integer in a print statement (and removing another type-cast of float to string).

There are some warnings remaining, but also a couple of compilation errors which it wasn't clear to me how to fix:
```
zed
/ceph-dan/Ublox_Linux_Library/linux_examples/Example2_StartRTCMBase.cpp: In function 'void setup()':
/ceph-dan/Ublox_Linux_Library/linux_examples/Example2_StartRTCMBase.cpp:52:8: error: 'class TwoWire' has no member named 'begin'
   Wire.begin();
        ^~~~~
/ceph-dan/Ublox_Linux_Library/linux_examples/Example2_StartRTCMBase.cpp:53:8: error: 'class TwoWire' has no member named 'setClock'
   Wire.setClock(400000); //Increase I2C clock speed to 400kHz
        ^~~~~~~~
```
... now, these calls may not actually be necessary in the implementation of TwoWire that you are using, but
I'm not sure, so I feel it's safer to let someone who knows about this deal with the issue.

I also experimented with moving forward the submodule from version 2.0.5 to version 2.1.5 of https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library, but this caused build errors with
header SPI.h not being found, that I was not sure how to resolve.

**Comment by danpovey** [comment]
... sorry, I actually intended to make this pull request to my own repository, but I'll leave it here as you may be able to comment.

**Comment by balamuruganky** [comment]
@danpovey : Thanks for using this code base and your contribution. Much appreciated!!!

**Comment by danpovey** [comment]
Thanks for merging, but please note that it has compilation errors, as I mentioned above!!  I don't want to break peoples' work...

**Comment by balamuruganky** [comment]
@danpovey : This PR has been removed now, Could you please check the i2c example and change the code accordingly? Thanks,

**Comment by danpovey** [comment]
OK, see #6

**Pull request merged**
